AWSTemplateFormatVersion: 2010-09-09
Description: Creates an Administrator group and Administrator IAM User
Parameters:
  InitialPassword:
    Type: String
    Description: Strong password for customer - will be reset on first login
    NoEcho: true

  Username:
    Type: String
    Description: The username to use

  AdministratorGroupName:
    Type: String
    Description: The admin group name

Resources:
  AdministratorGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Ref AdministratorGroupName
      Path: '/'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  AdministratorUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref Username
      LoginProfile:
        Password: !Ref InitialPassword
        PasswordResetRequired: true
      Path: '/'
      Groups:
        - !Ref AdministratorGroup

      

